[project]
name = "dayflow"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.0",
    "authlib>=1.7.2",
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "fastapi-jwt>=0.3.0",
    "joserfc>=1.7.4",
    "psycopg>=3.3.4",
    "pwdlib[argon2]>=0.3.0",
    "pydantic-settings>=2.14.2",
    "pydantic[email]>=2.13.4",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.51",
    "uvicorn>=0.52.0",
]
