"""fix jwt storage

Revision ID: 02500c99a661
Revises: 6d02063f79c3
Create Date: 2026-08-30 12:35:01.946823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02500c99a661'
down_revision: Union[str, Sequence[str], None] = '6d02063f79c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_jwt_storage', sa.Column('device', sa.String(), nullable=True))
    op.drop_column('user_jwt_storage', 'device_type')
    op.drop_column('user_jwt_storage', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_jwt_storage', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_jwt_storage', sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_jwt_storage', 'device')
    # ### end Alembic commands ###
