"""remove device from UsersJWTStorageORM

Revision ID: 6e8d0815fe03
Revises: 02500c99a661
Create Date: 2026-08-30 16:23:19.923827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8d0815fe03'
down_revision: Union[str, Sequence[str], None] = '02500c99a661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_jwt_storage', 'device')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_jwt_storage', sa.Column('device', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
