"""create chats and cards tables

Revision ID: 79457b9c93a6
Revises: 6e8d0815fe03
Create Date: 2026-09-14 15:06:15.628027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79457b9c93a6'
down_revision: Union[str, Sequence[str], None] = '6e8d0815fe03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_orm',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_orm_owner_id'), 'chat_orm', ['owner_id'], unique=False)
    op.create_table('card_orm',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('completed', 'in_progress', 'pending', 'cancelled', 'new', name='statuscard'), server_default='new', nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_orm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_orm_chat_id'), 'card_orm', ['chat_id'], unique=False)
    op.create_table('card_links',
    sa.Column('from_card_id', sa.Integer(), nullable=True),
    sa.Column('to_card_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('from_card_id <> to_card_id', name='ck_no_self_link'),
    sa.ForeignKeyConstraint(['from_card_id'], ['card_orm.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_card_id'], ['card_orm.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('from_card_id', 'to_card_id', name='uq_card_link')
    )
    op.create_index(op.f('ix_card_links_from_card_id'), 'card_links', ['from_card_id'], unique=False)
    op.create_index(op.f('ix_card_links_to_card_id'), 'card_links', ['to_card_id'], unique=False)
    op.drop_table('websockets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websockets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('websockets_pkey'))
    )
    op.drop_index(op.f('ix_card_links_to_card_id'), table_name='card_links')
    op.drop_index(op.f('ix_card_links_from_card_id'), table_name='card_links')
    op.drop_table('card_links')
    op.drop_index(op.f('ix_card_orm_chat_id'), table_name='card_orm')
    op.drop_table('card_orm')
    op.drop_index(op.f('ix_chat_orm_owner_id'), table_name='chat_orm')
    op.drop_table('chat_orm')
    # ### end Alembic commands ###
