"""add exp in UserJwtStorage

Revision ID: 9168cc08c0d1
Revises: 79457b9c93a6
Create Date: 2026-09-16 14:24:42.772448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9168cc08c0d1'
down_revision: Union[str, Sequence[str], None] = '79457b9c93a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_jwt_storage', sa.Column('exp', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_jwt_storage', 'exp')
    # ### end Alembic commands ###
